// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_jobtypes from "./routes/api/jobtypes.ts";
import * as $api_postings from "./routes/api/postings.ts";
import * as $api_sse from "./routes/api/sse.ts";
import * as $index from "./routes/index.tsx";
import * as $Filter from "./islands/Filter.tsx";
import * as $JobList from "./islands/JobList.tsx";
import * as $PostJob from "./islands/PostJob.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/jobtypes.ts": $api_jobtypes,
    "./routes/api/postings.ts": $api_postings,
    "./routes/api/sse.ts": $api_sse,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Filter.tsx": $Filter,
    "./islands/JobList.tsx": $JobList,
    "./islands/PostJob.tsx": $PostJob,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
